---
apiVersion: v1
kind: Service
metadata:
  name: ratehubux
  namespace: ratehubux
spec:
  selector:
    app: ratehubux
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
